# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyNewProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # -------------------------------------------------------
  # ✅ Required for iOS permissions (RNPermissions 5.4.4)
  # -------------------------------------------------------
permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Permission-Camera',             :path => "#{permissions_path}/Camera"
pod 'Permission-Microphone',         :path => "#{permissions_path}/Microphone"
pod 'Permission-LocationWhenInUse',  :path => "#{permissions_path}/LocationWhenInUse"
pod 'Permission-PhotoLibrary',       :path => "#{permissions_path}/PhotoLibrary"

  # ADD MORE IF NEEDED:
  # pod 'Permission-Notifications',     :path => "#{permissions_path}/Notifications"
  # pod 'Permission-Bluetooth',         :path => "#{permissions_path}/Bluetooth"
  # pod 'Permission-FaceID',            :path => "#{permissions_path}/FaceID"

  # -------------------------------------------------------

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end

# -----------------------------------------
# OneSignal Extension
# -----------------------------------------
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end
